Repository g12-4soat/techlanches-api, pull requests merged in 2024-03, with the labels that each got.

#9 refactoring usando aws secrets manager
  src/TechLanches/Adapter/Driven/TechLanches.Adapter.AWS.SecretsManager/AmazonSecretsManagerConfigurationProvider.cs
  src/TechLanches/Adapter/Driven/TechLanches.Adapter.AWS.SecretsManager/AmazonSecretsManagerConfigurationProviderExtensions.cs
  src/TechLanches/Adapter/Driven/TechLanches.Adapter.AWS.SecretsManager/AmazonSecretsManagerConfigurationSource.cs
  src/TechLanches/Adapter/Driven/TechLanches.Adapter.AWS.SecretsManager/TechLanches.Adapter.AWS.SecretsManager.csproj
  src/TechLanches/Adapter/Driven/TechLanches.Adapter.AWS.SecretsManager/TechLanchesDatabaseSecrets.cs
  src/TechLanches/Adapter/Driven/TechLanches.Adapter.SqlServer/DatabaseConfig.cs
  src/TechLanches/Adapter/Driven/TechLanches.Adapter.SqlServer/TechLanches.Adapter.SqlServer.csproj
  src/TechLanches/Adapter/Driver/TechLanches.Adapter.API/Program.cs
  src/TechLanches/Adapter/Driver/TechLanches.Adapter.API/TechLanches.Adapter.API.csproj
  src/TechLanches/Adapter/Driver/TechLanches.Adapter.FilaPedidos/Program.cs
  src/TechLanches/Dockerfile.API
  src/TechLanches/Dockerfile.Worker
  src/TechLanches/TechLanches.sln
Labels: enhancement

#11 Feature/auth
  src/TechLanches/Adapter/Driver/TechLanches.Adapter.API/Configuration/AuthenticationConfig.cs
  src/TechLanches/Adapter/Driver/TechLanches.Adapter.API/Endpoints/CheckoutEndpoints.cs
  src/TechLanches/Adapter/Driver/TechLanches.Adapter.API/Endpoints/PagamentoEndpoints.cs
  src/TechLanches/Adapter/Driver/TechLanches.Adapter.API/Endpoints/PedidoEndpoints.cs
  src/TechLanches/Adapter/Driver/TechLanches.Adapter.API/Endpoints/ProdutoEndpoints.cs
  src/TechLanches/Adapter/Driver/TechLanches.Adapter.API/Options/AuthenticationCognitoOptions.cs
  src/TechLanches/Adapter/Driver/TechLanches.Adapter.API/Program.cs
  src/TechLanches/Adapter/Driver/TechLanches.Adapter.API/TechLanches.Adapter.API.csproj
  src/TechLanches/Adapter/Driver/TechLanches.Adapter.API/appsettings.Development.json
  src/TechLanches/Adapter/Driver/TechLanches.Adapter.API/appsettings.Production.json
  src/TechLanches/Adapter/Driver/TechLanches.Adapter.API/appsettings.json
  src/TechLanches/Core/TechLanches.Application/Constantes/Constants.cs
  src/TechLanches/Core/TechLanches.Application/Controllers/ClienteController.cs
  src/TechLanches/Core/TechLanches.Application/Controllers/Interfaces/IPedidoController.cs
  src/TechLanches/Core/TechLanches.Application/Controllers/PedidoController.cs
  src/TechLanches/Core/TechLanches.Application/DTOs/PedidoRequestDTO.cs
  src/TechLanches/Core/TechLanches.Application/DTOs/UserTokenDTO.cs
  src/TechLanches/Core/TechLanches.Application/UseCases/Clientes/ClienteUseCases.cs
  src/TechLanches/Core/TechLanches.Application/UseCases/Pedidos/PedidoUseCases.cs
  test/TechLanches.UnitTests/Services/PedidoTest.cs
Labels: enhancement

#13 add secrets manager para cognito
  src/TechLanches/Adapter/Driven/TechLanches.Adapter.AWS.SecretsManager/TechLanchesCognitoSecrets.cs
  src/TechLanches/Adapter/Driver/TechLanches.Adapter.API/Configuration/AuthenticationConfig.cs
  src/TechLanches/Adapter/Driver/TechLanches.Adapter.API/Program.cs
Labels: enhancement

#14 fix secrets auth name
  src/TechLanches/Adapter/Driver/TechLanches.Adapter.API/Program.cs
Labels: bug, enhancement

#22 documentos da entrega
  docs/fase3/Tech_Challenge_-_SOAT_-_FASE_3_-_G12.docx
  docs/fase3/Tech_Challenge_-_SOAT_-_FASE_3_-_G12.pdf
Labels: documentation
